//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pashkovskiy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pashkovskiyEntities : DbContext
    {
        public pashkovskiyEntities()
            : base("name=pashkovskiyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Договоры> Договоры { get; set; }
        public virtual DbSet<Задачи_монтажа> Задачи_монтажа { get; set; }
        public virtual DbSet<Объекты> Объекты { get; set; }
        public virtual DbSet<Транспорт> Транспорт { get; set; }
    }
}
