//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pashkovskiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Задачи_монтажа
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Задачи_монтажа()
        {
            this.Транспорт = new HashSet<Транспорт>();
        }
    
        public int Id_задачи { get; set; }
        public int Id_договор { get; set; }
        public System.DateTime Плановая_дата { get; set; }
        public string Статус { get; set; }
    
        public virtual Договоры Договоры { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Транспорт> Транспорт { get; set; }
    }
}
