//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pashkovskiy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Транспорт
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Транспорт()
        {
            this.Задачи_монтажа = new HashSet<Задачи_монтажа>();
        }
    
        public int id_транспорта { get; set; }
        public string Гос_номер { get; set; }
        public string Марка_машины { get; set; }
        public string тип { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задачи_монтажа> Задачи_монтажа { get; set; }
    }
}
